--------------
-- BHPBIO POST

ALTER TABLE dbo.BhpbioApprovalData
	ADD CONSTRAINT FK_BhpbioApprovalData_User FOREIGN KEY (UserId)
		REFERENCES dbo.SecurityUser (UserId)
GO

ALTER TABLE dbo.BhpbioApprovalDigblock
	ADD CONSTRAINT FK_BhpbioApprovalDigbock_User FOREIGN KEY (UserId)
		REFERENCES dbo.SecurityUser (UserId)
GO

-- Add the default group / role association
DECLARE @GroupId INT

INSERT INTO dbo.SecurityGroup
	(NTAccountName, NTAccountSid)
SELECT 'SNOWDEN\Domain Users', NULL

SET @GroupId = Scope_Identity()

INSERT INTO dbo.SecurityRoleAssignment
	(RoleId, UserId, GroupId)
SELECT RoleId, NULL, @GroupId
FROM dbo.SecurityRole
WHERE RoleId = 'REC_ADMIN'

INSERT INTO dbo.SecurityGroup
	(NTAccountName, NTAccountSid)
SELECT 'APAC\Domain Users', NULL

SET @GroupId = Scope_Identity()

INSERT INTO dbo.SecurityRoleAssignment
	(RoleId, UserId, GroupId)
VALUES
	('REC_VIEW', NULL, @GroupId)
GO

-- reset the setting!
UPDATE dbo.Setting
SET Value = 'FALSE'
WHERE Setting_Id = 'USE_ACTIVE_DIRECTORY'


-- fix up the broken roles (copied from data pop scripts)
BEGIN TRANSACTION

DELETE FROM dbo.BhpbioSecurityRoleLocation

DECLARE @Roles TABLE
(
	RoleId VARCHAR(31) COLLATE DATABASE_DEFAULT NOT NULL,
	Description VARCHAR(31) COLLATE DATABASE_DEFAULT NOT NULL,
	LocationId INT NOT NULL
)

INSERT INTO @Roles
SELECT 'BHP_' + REPLACE(Upper(Name), ' ', ''), Name + ' User', l.Location_ID
FROM dbo.Location AS l
	INNER JOIN dbo.LocationType AS lt
		ON l.Location_Type_Id = lt.Location_Type_Id
WHERE lt.Description IN ('Company', 'Hub')

INSERT INTO dbo.SecurityRole
	(RoleId, Description)
SELECT RoleId, Description
FROM @Roles
WHERE RoleId NOT IN (SELECT RoleId FROM @Roles)

INSERT INTO dbo.BhpbioSecurityRoleLocation
SELECT RoleId, LocationId
FROM @Roles

COMMIT TRANSACTION

--------------------------------
-- REASSIGN OPTIONS & ROLES !!!!

-- clear out all of the existing settings
DELETE
FROM dbo.SecurityRoleOption

-- remove unused roles
DELETE
FROM dbo.SecurityRole
WHERE RoleId IN ('REC_GEO', 'REC_SNR_USER')

-- REC_ADMIN
INSERT INTO dbo.SecurityRoleOption
	(Role_Id, Application_Id, Option_Id)
SELECT 'REC_ADMIN', 'REC', Option_Id
FROM dbo.SecurityOption

-- BHP_WAIO
INSERT INTO dbo.SecurityRoleOption
	(Role_Id, Application_Id, Option_Id)
SELECT 'BHP_WAIO', 'REC', 'ANALYSIS_MINE_PLAN_COMPARISON' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ANALYSIS_RECALC_LOGIC' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ANALYSIS_SPATIAL_TOOL' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ANALYSIS_SPATIAL_VARIANCE_SETUP' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'APPROVAL_DIGBLOCK' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'APPROVAL_FREPORT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'APPROVAL_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'APPROVAL_OTHER' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'DIGBLOCK_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'DIGBLOCK_TREE' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'DIGBLOCK_VIEW' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ANALYSIS_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'DIGBLOCK_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'REC_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'REPORT_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'MANAGE_IMPORT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'PORT_GRANT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_10' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_11' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_12' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_13' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_14' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_6' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_7' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_8' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'Report_9' UNION ALL
SELECT 'BHP_WAIO', 'REC','ReportGroup_1' UNION ALL
SELECT 'BHP_WAIO', 'REC','ReportGroup_2' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'REPORT_ADHOC_REPORTING' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'REPORT_ADMIN' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'REPORT_UPLOAD' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ADMIN_ROLE' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'ADMIN_USER' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_ADJUSTMENT_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_MANUAL_ADJUST_VIEW' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_SURVEY_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_SURVEY_VIEW' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'STOCKPILE_VIEW' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'MANAGE_BHPBIO_CUSTOM_FIELDS_CONFIGURATION' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_DATA_EXCEPTIONS' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_GRADES' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_BULK_CORRECTION' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_BULK_EDIT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_CORRECTION_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_MANAGEMENT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_NAME_RESOLUTION' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_HAULAGE_NEW_RECORD' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_LOCATIONS' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_MATERIAL_TYPES' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_RECALC_VIEW' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_STOCKPILE_GROUP' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_SYSTEM_SETTINGS' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_UI_MANAGEMENT' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_WEIGHTOMETER_SAMPLE' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'UTILITIES_WEIGHTOMETER_SAMPLE_LIST' UNION ALL
SELECT 'BHP_WAIO', 'REC', 'VIEW_EVENT'

-- BHP_AREAC, BHP_NJV, BHP_YANDI, BHP_YARRIE
INSERT INTO dbo.SecurityRoleOption
	(Role_Id, Application_Id, Option_Id)
SELECT secRole.RoleId, 'REC', secOption.OptionId
FROM
	(
		SELECT 'BHP_AREAC' AS RoleId UNION ALL
		SELECT 'BHP_NJV' UNION ALL
		SELECT 'BHP_YANDI' UNION ALL
		SELECT 'BHP_YARRIE'
	) AS secRole
	CROSS JOIN
	(
		SELECT 'ANALYSIS_MINE_PLAN_COMPARISON' AS OptionId UNION ALL
		SELECT 'ANALYSIS_RECALC_LOGIC' UNION ALL
		SELECT 'ANALYSIS_SPATIAL_TOOL' UNION ALL
		SELECT 'ANALYSIS_SPATIAL_VARIANCE_SETUP' UNION ALL
		SELECT 'APPROVAL_DIGBLOCK' UNION ALL
		SELECT 'APPROVAL_FREPORT' UNION ALL
		SELECT 'APPROVAL_GRANT' UNION ALL
		SELECT 'APPROVAL_OTHER' UNION ALL
		SELECT 'DIGBLOCK_LIST' UNION ALL
		SELECT 'DIGBLOCK_TREE' UNION ALL
		SELECT 'DIGBLOCK_VIEW' UNION ALL
		SELECT 'ANALYSIS_GRANT' UNION ALL
		SELECT 'DIGBLOCK_GRANT' UNION ALL
		SELECT 'REC_GRANT' UNION ALL
		SELECT 'REPORT_GRANT' UNION ALL
		SELECT 'STOCKPILE_GRANT' UNION ALL
		SELECT 'UTILITIES_GRANT' UNION ALL
		SELECT 'MANAGE_IMPORT' UNION ALL
		SELECT 'PORT_GRANT' UNION ALL
		SELECT 'Report_10' UNION ALL
		SELECT 'Report_11' UNION ALL
		SELECT 'Report_12' UNION ALL
		SELECT 'Report_13' UNION ALL
		SELECT 'Report_14' UNION ALL
		SELECT 'Report_6' UNION ALL
		SELECT 'Report_7' UNION ALL
		SELECT 'Report_8' UNION ALL
		SELECT 'Report_9' UNION ALL
		SELECT 'ReportGroup_1' UNION ALL
		SELECT 'ReportGroup_2' UNION ALL
		SELECT 'STOCKPILE_ADJUSTMENT_LIST' UNION ALL
		SELECT 'STOCKPILE_LIST' UNION ALL
		SELECT 'STOCKPILE_MANUAL_ADJUST_VIEW' UNION ALL
		SELECT 'STOCKPILE_SURVEY_LIST' UNION ALL
		SELECT 'STOCKPILE_SURVEY_VIEW' UNION ALL
		SELECT 'STOCKPILE_VIEW' UNION ALL
		SELECT 'UTILITIES_DATA_EXCEPTIONS' UNION ALL
		SELECT 'UTILITIES_GRADES' UNION ALL
		SELECT 'UTILITIES_HAULAGE_BULK_CORRECTION' UNION ALL
		SELECT 'UTILITIES_HAULAGE_BULK_EDIT' UNION ALL
		SELECT 'UTILITIES_HAULAGE_CORRECTION_LIST' UNION ALL
		SELECT 'UTILITIES_HAULAGE_LIST' UNION ALL
		SELECT 'UTILITIES_HAULAGE_MANAGEMENT' UNION ALL
		SELECT 'UTILITIES_HAULAGE_NAME_RESOLUTION' UNION ALL
		SELECT 'UTILITIES_HAULAGE_NEW_RECORD' UNION ALL
		SELECT 'UTILITIES_LOCATIONS' UNION ALL
		SELECT 'UTILITIES_MATERIAL_TYPES' UNION ALL
		SELECT 'UTILITIES_STOCKPILE_GROUP' UNION ALL
		SELECT 'UTILITIES_WEIGHTOMETER_SAMPLE' UNION ALL
		SELECT 'UTILITIES_WEIGHTOMETER_SAMPLE_LIST'
	) AS secOption

-- REC_VIEW
INSERT INTO dbo.SecurityRoleOption
	(Role_Id, Application_Id, Option_Id)
SELECT 'REC_VIEW', 'REC', 'ANALYSIS_MINE_PLAN_COMPARISON' UNION ALL
SELECT 'REC_VIEW', 'REC', 'ANALYSIS_RECALC_LOGIC' UNION ALL
SELECT 'REC_VIEW', 'REC', 'ANALYSIS_SPATIAL_TOOL' UNION ALL
SELECT 'REC_VIEW', 'REC', 'ANALYSIS_SPATIAL_VARIANCE_SETUP' UNION ALL
SELECT 'REC_VIEW', 'REC', 'DIGBLOCK_LIST' UNION ALL
SELECT 'REC_VIEW', 'REC', 'DIGBLOCK_TREE' UNION ALL
SELECT 'REC_VIEW', 'REC', 'DIGBLOCK_VIEW' UNION ALL
SELECT 'REC_VIEW', 'REC', 'ANALYSIS_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'DIGBLOCK_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'REC_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'REPORT_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'PORT_GRANT' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_10' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_11' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_12' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_13' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_14' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_6' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_7' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_8' UNION ALL
SELECT 'REC_VIEW', 'REC', 'Report_9' UNION ALL
SELECT 'REC_VIEW', 'REC','ReportGroup_1' UNION ALL
SELECT 'REC_VIEW', 'REC','ReportGroup_2' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_ADJUSTMENT_LIST' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_LIST' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_MANUAL_ADJUST_VIEW' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_SURVEY_LIST' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_SURVEY_VIEW' UNION ALL
SELECT 'REC_VIEW', 'REC', 'STOCKPILE_VIEW'
