// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.2.0
//    <NameSpace>Snowden.Reconcilor.Bhpbio.DataStaging</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>Collections</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Snowden.Reconcilor.Bhpbio.DataStaging
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class BlockOutAndBlastedEventType
    {

        private SourceModelDescriptorType sourceModelDetailField;

        private PatternDetailsType patternDetailsField;

        public System.DateTime Timestamp { get; set; }
        public bool IsReblockOut { get; set; }
        public string ResponsibleUsername { get; set; }
        public SourceModelDescriptorType SourceModelDetail { get; set; }
        public PatternDetailsType PatternDetails { get; set; }
    }

    public partial class SourceModelDescriptorType
    {

        public string ModelFile { get; set; }
        public string ModelType { get; set; }
    }

    public partial class MiningPointType
    {

        public double Easting { get; set; }
        public double Northing { get; set; }
        public int PointNumber { get; set; }
        public double ToeRL { get; set; }
    }

    public partial class AnalyteType
    {

        public string AnalyteName { get; set; }
        public double Value { get; set; }
    }

    public partial class QualityType
    {

        private List<AnalyteType> analytesField;

        [XmlElement(ElementName = "QualityType")]
        public string QualityType1 { get; set; }
        public double QualityTypeSplitPercentage { get; set; }
        [XmlElement("Analytes")]
        public List<AnalyteType> Analytes { get; set; }

        public QualityType()
        {
            this.Analytes = new List<AnalyteType>();
        }
    }

    public partial class GradeSetType
    {

        private List<QualityType> qualitySetField;

        [XmlElement("GradeSetType")]
        public string GradeSetType1 { get; set; }
        [XmlElement("QualitySet")]
        public List<QualityType> QualitySet { get; set; }

        public GradeSetType()
        {
            this.QualitySet = new List<QualityType>();
        }
    }

    public partial class ModelBlockType
    {

        private List<GradeSetType> gradeSetField;

        public string ModelType { get; set; }
        public double Tonnes { get; set; }
        public double Volume { get; set; }
        public double Density { get; set; }
        public string OreType { get; set; }
        public string Designation { get; set; }
        public string MaterialCode { get; set; }
        public string LastModifiedUserName { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        [XmlElement("GradeSet")]
        public List<GradeSetType> GradeSet { get; set; }

        public ModelBlockType()
        {
            this.GradeSet = new List<GradeSetType>();
        }
    }

    public partial class BlockType
    {

        private List<ModelBlockType> modelBlockField;

        private MiningPointType centroidField;

        private List<MiningPointType> polygonPointField;

        public string Name { get; set; }
        public string BlockGUID { get; set; }
        public int BlockNumber { get; set; }
        public string FlitchGUID { get; set; }
        public string GeoType { get; set; }
        public System.DateTime DateBlocked { get; set; }
        public string Stratigraphy { get; set; }
        public int StratNum { get; set; }
        [XmlElement("ModelBlock")]
        public List<ModelBlockType> ModelBlock { get; set; }
        public MiningPointType Centroid { get; set; }
        [XmlElement("PolygonPoint")]
        public List<MiningPointType> PolygonPoint { get; set; }
        public string ChangeState { get; set; }

        public BlockType()
        {
            this.PolygonPoint = new List<MiningPointType>();
            this.ModelBlock = new List<ModelBlockType>();
        }
        public int? Weathering { get; set; }
    }

    public partial class PatternDetailsType
    {

        private List<BlockType> blockField;

        public string PatternGUID { get; set; }
        public string PatternNumber { get; set; }
        public string Name { get; set; }
        public string SiteId { get; set; }
        public string MQ2SiteCode { get; set; }
        public string OrebodyId { get; set; }
        public string PitId_Log { get; set; }
        public string PitId_Phy { get; set; }
        public string PitId_MQ2 { get; set; }
        public string Bench { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateAccepted { get; set; }
        public string AcceptedByUserName { get; set; }
        public string ApprovedByUserName { get; set; }
        public string BlastID { get; set; }
        public string BlastStatus { get; set; }
        public System.DateTime BlastStatusChangeDateTime { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlastStatusChangeDateTimeSpecified { get; set; }
        public string ExternalLocationID { get; set; }
        public string JVOwner { get; set; }
        [XmlElement("Block")]
        public List<BlockType> Block { get; set; }

        public PatternDetailsType()
        {
            this.Block = new List<BlockType>();
        }
    }
}
