'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MaterialTrackerService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MT/v1.0", ConfigurationName:="MaterialTrackerService.IM_MT_DS")>  _
    Public Interface IM_MT_DS
        
        'CODEGEN: Generating message contract since the operation retrievePortBalances is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve"& _ 
            "PortBalances", ReplyAction:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MT/v1.0/IM_MT_DS/"& _ 
            "retrievePortBalancesResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function retrievePortBalances(ByVal request As MaterialTrackerService.retrievePortBalancesRequest1) As MaterialTrackerService.retrievePortBalancesResponse1
        
        'CODEGEN: Generating message contract since the operation retrieveShipping is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve"& _ 
            "Shipping", ReplyAction:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MT/v1.0/IM_MT_DS/"& _ 
            "retrieveShippingResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function retrieveShipping(ByVal request As MaterialTrackerService.retrieveShippingRequest1) As MaterialTrackerService.retrieveShippingResponse1
        
        'CODEGEN: Generating message contract since the operation retrieveMETBalancing is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve"& _ 
            "METBalancing", ReplyAction:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MT/v1.0/IM_MT_DS/"& _ 
            "retrieveMETBalancingResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function retrieveMETBalancing(ByVal request As MaterialTrackerService.retrieveMETBalancingRequest1) As MaterialTrackerService.retrieveMETBalancingResponse1
        
        'CODEGEN: Generating message contract since the operation retrievePortBlending is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve"& _ 
            "PortBlending", ReplyAction:="http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MT/v1.0/IM_MT_DS/"& _ 
            "retrievePortBlendingResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function retrievePortBlending(ByVal request As MaterialTrackerService.retrievePortBlendingRequest1) As MaterialTrackerService.retrievePortBlendingResponse1
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrievePortBalancesRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class BlendingMovementType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sourceHubField As String
        
        Private destinationHubField As String
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        Private loadSitesField As String
        
        Private sourceProductField As String
        
        Private destinationProductField As String
        
        Private sourceProductSizeField As String
        
        Private destinationProductSizeField As String
        
        Private tonnesField As Decimal
        
        Private tonnesFieldSpecified As Boolean
        
        Private gradeField() As Grade
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property SourceHub() As String
            Get
                Return Me.sourceHubField
            End Get
            Set
                Me.sourceHubField = value
                Me.RaisePropertyChanged("SourceHub")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property DestinationHub() As String
            Get
                Return Me.destinationHubField
            End Get
            Set
                Me.destinationHubField = value
                Me.RaisePropertyChanged("DestinationHub")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EndDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("EndDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property LoadSites() As String
            Get
                Return Me.loadSitesField
            End Get
            Set
                Me.loadSitesField = value
                Me.RaisePropertyChanged("LoadSites")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property SourceProduct() As String
            Get
                Return Me.sourceProductField
            End Get
            Set
                Me.sourceProductField = value
                Me.RaisePropertyChanged("SourceProduct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property DestinationProduct() As String
            Get
                Return Me.destinationProductField
            End Get
            Set
                Me.destinationProductField = value
                Me.RaisePropertyChanged("DestinationProduct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property SourceProductSize() As String
            Get
                Return Me.sourceProductSizeField
            End Get
            Set
                Me.sourceProductSizeField = value
                Me.RaisePropertyChanged("SourceProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property DestinationProductSize() As String
            Get
                Return Me.destinationProductSizeField
            End Get
            Set
                Me.destinationProductSizeField = value
                Me.RaisePropertyChanged("DestinationProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property Tonnes() As Decimal
            Get
                Return Me.tonnesField
            End Get
            Set
                Me.tonnesField = value
                Me.RaisePropertyChanged("Tonnes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TonnesSpecified() As Boolean
            Get
                Return Me.tonnesFieldSpecified
            End Get
            Set
                Me.tonnesFieldSpecified = value
                Me.RaisePropertyChanged("TonnesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Grade", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property Grade() As Grade()
            Get
                Return Me.gradeField
            End Get
            Set
                Me.gradeField = value
                Me.RaisePropertyChanged("Grade")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class Grade
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        Private sampleValueField As Decimal
        
        Private sampleValueFieldSpecified As Boolean
        
        Private headValueField As Decimal
        
        Private headValueFieldSpecified As Boolean
        
        Private finesValueField As Decimal
        
        Private finesValueFieldSpecified As Boolean
        
        Private lumpValueField As Decimal
        
        Private lumpValueFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property SampleValue() As Decimal
            Get
                Return Me.sampleValueField
            End Get
            Set
                Me.sampleValueField = value
                Me.RaisePropertyChanged("SampleValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SampleValueSpecified() As Boolean
            Get
                Return Me.sampleValueFieldSpecified
            End Get
            Set
                Me.sampleValueFieldSpecified = value
                Me.RaisePropertyChanged("SampleValueSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property HeadValue() As Decimal
            Get
                Return Me.headValueField
            End Get
            Set
                Me.headValueField = value
                Me.RaisePropertyChanged("HeadValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeadValueSpecified() As Boolean
            Get
                Return Me.headValueFieldSpecified
            End Get
            Set
                Me.headValueFieldSpecified = value
                Me.RaisePropertyChanged("HeadValueSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property FinesValue() As Decimal
            Get
                Return Me.finesValueField
            End Get
            Set
                Me.finesValueField = value
                Me.RaisePropertyChanged("FinesValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FinesValueSpecified() As Boolean
            Get
                Return Me.finesValueFieldSpecified
            End Get
            Set
                Me.finesValueFieldSpecified = value
                Me.RaisePropertyChanged("FinesValueSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property LumpValue() As Decimal
            Get
                Return Me.lumpValueField
            End Get
            Set
                Me.lumpValueField = value
                Me.RaisePropertyChanged("LumpValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LumpValueSpecified() As Boolean
            Get
                Return Me.lumpValueFieldSpecified
            End Get
            Set
                Me.lumpValueFieldSpecified = value
                Me.RaisePropertyChanged("LumpValueSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class METBalResultType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private siteField As String
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        Private plantNameField As String
        
        Private streamNameField As String
        
        Private weightometerField As String
        
        Private productSizeField As String
        
        Private dryTonnesField As Decimal
        
        Private dryTonnesFieldSpecified As Boolean
        
        Private wetTonnesField As Decimal
        
        Private wetTonnesFieldSpecified As Boolean
        
        Private splitCycleField As String
        
        Private splitPlantField As String
        
        Private gradeField() As Grade
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Site() As String
            Get
                Return Me.siteField
            End Get
            Set
                Me.siteField = value
                Me.RaisePropertyChanged("Site")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EndDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("EndDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property PlantName() As String
            Get
                Return Me.plantNameField
            End Get
            Set
                Me.plantNameField = value
                Me.RaisePropertyChanged("PlantName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property StreamName() As String
            Get
                Return Me.streamNameField
            End Get
            Set
                Me.streamNameField = value
                Me.RaisePropertyChanged("StreamName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property Weightometer() As String
            Get
                Return Me.weightometerField
            End Get
            Set
                Me.weightometerField = value
                Me.RaisePropertyChanged("Weightometer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property ProductSize() As String
            Get
                Return Me.productSizeField
            End Get
            Set
                Me.productSizeField = value
                Me.RaisePropertyChanged("ProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property DryTonnes() As Decimal
            Get
                Return Me.dryTonnesField
            End Get
            Set
                Me.dryTonnesField = value
                Me.RaisePropertyChanged("DryTonnes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DryTonnesSpecified() As Boolean
            Get
                Return Me.dryTonnesFieldSpecified
            End Get
            Set
                Me.dryTonnesFieldSpecified = value
                Me.RaisePropertyChanged("DryTonnesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property WetTonnes() As Decimal
            Get
                Return Me.wetTonnesField
            End Get
            Set
                Me.wetTonnesField = value
                Me.RaisePropertyChanged("WetTonnes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WetTonnesSpecified() As Boolean
            Get
                Return Me.wetTonnesFieldSpecified
            End Get
            Set
                Me.wetTonnesFieldSpecified = value
                Me.RaisePropertyChanged("WetTonnesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property SplitCycle() As String
            Get
                Return Me.splitCycleField
            End Get
            Set
                Me.splitCycleField = value
                Me.RaisePropertyChanged("SplitCycle")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property SplitPlant() As String
            Get
                Return Me.splitPlantField
            End Get
            Set
                Me.splitPlantField = value
                Me.RaisePropertyChanged("SplitPlant")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Grade", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property Grade() As Grade()
            Get
                Return Me.gradeField
            End Get
            Set
                Me.gradeField = value
                Me.RaisePropertyChanged("Grade")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class HubItemType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private hubField As String
        
        Private hubProductField As String
        
        Private hubProductSizeField As String
        
        Private tonnesField As Decimal
        
        Private tonnesFieldSpecified As Boolean
        
        Private gradeField() As Grade
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Hub() As String
            Get
                Return Me.hubField
            End Get
            Set
                Me.hubField = value
                Me.RaisePropertyChanged("Hub")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property HubProduct() As String
            Get
                Return Me.hubProductField
            End Get
            Set
                Me.hubProductField = value
                Me.RaisePropertyChanged("HubProduct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property HubProductSize() As String
            Get
                Return Me.hubProductSizeField
            End Get
            Set
                Me.hubProductSizeField = value
                Me.RaisePropertyChanged("HubProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property Tonnes() As Decimal
            Get
                Return Me.tonnesField
            End Get
            Set
                Me.tonnesField = value
                Me.RaisePropertyChanged("Tonnes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TonnesSpecified() As Boolean
            Get
                Return Me.tonnesFieldSpecified
            End Get
            Set
                Me.tonnesFieldSpecified = value
                Me.RaisePropertyChanged("TonnesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Grade", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property Grade() As Grade()
            Get
                Return Me.gradeField
            End Get
            Set
                Me.gradeField = value
                Me.RaisePropertyChanged("Grade")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class NominationItemType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemNoField As String
        
        Private customerNoField As String
        
        Private customerNameField As String
        
        Private lastAuthorisedDateField As Date
        
        Private lastAuthorisedDateFieldSpecified As Boolean
        
        Private officialFinishTimeField As Date
        
        Private officialFinishTimeFieldSpecified As Boolean
        
        Private shippedProductField As String
        
        Private shippedProductSizeField As String
        
        Private cOAField As Date
        
        Private cOAFieldSpecified As Boolean
        
        Private oversizeField As Decimal
        
        Private oversizeFieldSpecified As Boolean
        
        Private undersizeField As Decimal
        
        Private undersizeFieldSpecified As Boolean
        
        Private hubItemField() As HubItemType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property ItemNo() As String
            Get
                Return Me.itemNoField
            End Get
            Set
                Me.itemNoField = value
                Me.RaisePropertyChanged("ItemNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property CustomerNo() As String
            Get
                Return Me.customerNoField
            End Get
            Set
                Me.customerNoField = value
                Me.RaisePropertyChanged("CustomerNo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property CustomerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set
                Me.customerNameField = value
                Me.RaisePropertyChanged("CustomerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property LastAuthorisedDate() As Date
            Get
                Return Me.lastAuthorisedDateField
            End Get
            Set
                Me.lastAuthorisedDateField = value
                Me.RaisePropertyChanged("LastAuthorisedDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LastAuthorisedDateSpecified() As Boolean
            Get
                Return Me.lastAuthorisedDateFieldSpecified
            End Get
            Set
                Me.lastAuthorisedDateFieldSpecified = value
                Me.RaisePropertyChanged("LastAuthorisedDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property OfficialFinishTime() As Date
            Get
                Return Me.officialFinishTimeField
            End Get
            Set
                Me.officialFinishTimeField = value
                Me.RaisePropertyChanged("OfficialFinishTime")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OfficialFinishTimeSpecified() As Boolean
            Get
                Return Me.officialFinishTimeFieldSpecified
            End Get
            Set
                Me.officialFinishTimeFieldSpecified = value
                Me.RaisePropertyChanged("OfficialFinishTimeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property ShippedProduct() As String
            Get
                Return Me.shippedProductField
            End Get
            Set
                Me.shippedProductField = value
                Me.RaisePropertyChanged("ShippedProduct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property ShippedProductSize() As String
            Get
                Return Me.shippedProductSizeField
            End Get
            Set
                Me.shippedProductSizeField = value
                Me.RaisePropertyChanged("ShippedProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property COA() As Date
            Get
                Return Me.cOAField
            End Get
            Set
                Me.cOAField = value
                Me.RaisePropertyChanged("COA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property COASpecified() As Boolean
            Get
                Return Me.cOAFieldSpecified
            End Get
            Set
                Me.cOAFieldSpecified = value
                Me.RaisePropertyChanged("COASpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property Oversize() As Decimal
            Get
                Return Me.oversizeField
            End Get
            Set
                Me.oversizeField = value
                Me.RaisePropertyChanged("Oversize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OversizeSpecified() As Boolean
            Get
                Return Me.oversizeFieldSpecified
            End Get
            Set
                Me.oversizeFieldSpecified = value
                Me.RaisePropertyChanged("OversizeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property Undersize() As Decimal
            Get
                Return Me.undersizeField
            End Get
            Set
                Me.undersizeField = value
                Me.RaisePropertyChanged("Undersize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property UndersizeSpecified() As Boolean
            Get
                Return Me.undersizeFieldSpecified
            End Get
            Set
                Me.undersizeFieldSpecified = value
                Me.RaisePropertyChanged("UndersizeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("HubItem", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property HubItem() As HubItemType()
            Get
                Return Me.hubItemField
            End Get
            Set
                Me.hubItemField = value
                Me.RaisePropertyChanged("HubItem")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class ShippingTransactionType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nominationKeyField As String
        
        Private vesselNameField As String
        
        Private nominationItemField As NominationItemType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property NominationKey() As String
            Get
                Return Me.nominationKeyField
            End Get
            Set
                Me.nominationKeyField = value
                Me.RaisePropertyChanged("NominationKey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property VesselName() As String
            Get
                Return Me.vesselNameField
            End Get
            Set
                Me.vesselNameField = value
                Me.RaisePropertyChanged("VesselName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property NominationItem() As NominationItemType
            Get
                Return Me.nominationItemField
            End Get
            Set
                Me.nominationItemField = value
                Me.RaisePropertyChanged("NominationItem")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class PortBalancesStockpileType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private balanceDateField As Date
        
        Private balanceDateFieldSpecified As Boolean
        
        Private hubField As String
        
        Private tonnesField As Decimal
        
        Private tonnesFieldSpecified As Boolean
        
        Private productField As String
        
        Private productSizeField As String
        
        Private gradeField() As Grade
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property BalanceDate() As Date
            Get
                Return Me.balanceDateField
            End Get
            Set
                Me.balanceDateField = value
                Me.RaisePropertyChanged("BalanceDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property BalanceDateSpecified() As Boolean
            Get
                Return Me.balanceDateFieldSpecified
            End Get
            Set
                Me.balanceDateFieldSpecified = value
                Me.RaisePropertyChanged("BalanceDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property Hub() As String
            Get
                Return Me.hubField
            End Get
            Set
                Me.hubField = value
                Me.RaisePropertyChanged("Hub")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property Tonnes() As Decimal
            Get
                Return Me.tonnesField
            End Get
            Set
                Me.tonnesField = value
                Me.RaisePropertyChanged("Tonnes")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TonnesSpecified() As Boolean
            Get
                Return Me.tonnesFieldSpecified
            End Get
            Set
                Me.tonnesFieldSpecified = value
                Me.RaisePropertyChanged("TonnesSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property Product() As String
            Get
                Return Me.productField
            End Get
            Set
                Me.productField = value
                Me.RaisePropertyChanged("Product")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property ProductSize() As String
            Get
                Return Me.productSizeField
            End Get
            Set
                Me.productSizeField = value
                Me.RaisePropertyChanged("ProductSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Grade", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property Grade() As Grade()
            Get
                Return Me.gradeField
            End Get
            Set
                Me.gradeField = value
                Me.RaisePropertyChanged("Grade")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class Status
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusMessageField As String
        
        Private statusFlagField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property StatusMessage() As String
            Get
                Return Me.statusMessageField
            End Get
            Set
                Me.statusMessageField = value
                Me.RaisePropertyChanged("StatusMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property StatusFlag() As Boolean
            Get
                Return Me.statusFlagField
            End Get
            Set
                Me.statusFlagField = value
                Me.RaisePropertyChanged("StatusFlag")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrievePortBalancesResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As Status
        
        Private portBalancesField() As PortBalancesStockpileType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Stockpile", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property PortBalances() As PortBalancesStockpileType()
            Get
                Return Me.portBalancesField
            End Get
            Set
                Me.portBalancesField = value
                Me.RaisePropertyChanged("PortBalances")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrievePortBalancesRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrievePortBalancesRequest As MaterialTrackerService.RetrievePortBalancesRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrievePortBalancesRequest As MaterialTrackerService.RetrievePortBalancesRequest)
            MyBase.New
            Me.RetrievePortBalancesRequest = RetrievePortBalancesRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrievePortBalancesResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrievePortBalancesResponse As MaterialTrackerService.RetrievePortBalancesResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrievePortBalancesResponse As MaterialTrackerService.RetrievePortBalancesResponse)
            MyBase.New
            Me.RetrievePortBalancesResponse = RetrievePortBalancesResponse
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrieveShippingRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EndDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("EndDateSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrieveShippingResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As Status
        
        Private shippingField() As ShippingTransactionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Transaction", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Shipping() As ShippingTransactionType()
            Get
                Return Me.shippingField
            End Get
            Set
                Me.shippingField = value
                Me.RaisePropertyChanged("Shipping")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveShippingRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrieveShippingRequest As MaterialTrackerService.RetrieveShippingRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrieveShippingRequest As MaterialTrackerService.RetrieveShippingRequest)
            MyBase.New
            Me.RetrieveShippingRequest = RetrieveShippingRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveShippingResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrieveShippingResponse As MaterialTrackerService.RetrieveShippingResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrieveShippingResponse As MaterialTrackerService.RetrieveShippingResponse)
            MyBase.New
            Me.RetrieveShippingResponse = RetrieveShippingResponse
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrieveMETBalancingRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EndDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("EndDateSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrieveMETBalancingResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As Status
        
        Private mETBalancingField() As METBalResultType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Result", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property METBalancing() As METBalResultType()
            Get
                Return Me.mETBalancingField
            End Get
            Set
                Me.mETBalancingField = value
                Me.RaisePropertyChanged("METBalancing")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveMETBalancingRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrieveMETBalancingRequest As MaterialTrackerService.RetrieveMETBalancingRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrieveMETBalancingRequest As MaterialTrackerService.RetrieveMETBalancingRequest)
            MyBase.New
            Me.RetrieveMETBalancingRequest = RetrieveMETBalancingRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrieveMETBalancingResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrieveMETBalancingResponse As MaterialTrackerService.RetrieveMETBalancingResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrieveMETBalancingResponse As MaterialTrackerService.RetrieveMETBalancingResponse)
            MyBase.New
            Me.RetrieveMETBalancingResponse = RetrieveMETBalancingResponse
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrievePortBlendingRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private startDateField As Date
        
        Private startDateFieldSpecified As Boolean
        
        Private endDateField As Date
        
        Private endDateFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StartDateSpecified() As Boolean
            Get
                Return Me.startDateFieldSpecified
            End Get
            Set
                Me.startDateFieldSpecified = value
                Me.RaisePropertyChanged("StartDateSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property EndDateSpecified() As Boolean
            Get
                Return Me.endDateFieldSpecified
            End Get
            Set
                Me.endDateFieldSpecified = value
                Me.RaisePropertyChanged("EndDateSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService")>  _
    Partial Public Class RetrievePortBlendingResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As Status
        
        Private portBlendingField() As BlendingMovementType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Movement", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property PortBlending() As BlendingMovementType()
            Get
                Return Me.portBlendingField
            End Get
            Set
                Me.portBlendingField = value
                Me.RaisePropertyChanged("PortBlending")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrievePortBlendingRequest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrievePortBlendingRequest As MaterialTrackerService.RetrievePortBlendingRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrievePortBlendingRequest As MaterialTrackerService.RetrievePortBlendingRequest)
            MyBase.New
            Me.RetrievePortBlendingRequest = RetrievePortBlendingRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class retrievePortBlendingResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.bhpbilliton.com/waio/F1F2F3DataService", Order:=0)>  _
        Public RetrievePortBlendingResponse As MaterialTrackerService.RetrievePortBlendingResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RetrievePortBlendingResponse As MaterialTrackerService.RetrievePortBlendingResponse)
            MyBase.New
            Me.RetrievePortBlendingResponse = RetrievePortBlendingResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IM_MT_DSChannel
        Inherits MaterialTrackerService.IM_MT_DS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class M_MT_DSClient
        Inherits System.ServiceModel.ClientBase(Of MaterialTrackerService.IM_MT_DS)
        Implements MaterialTrackerService.IM_MT_DS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MaterialTrackerService_IM_MT_DS_retrievePortBalances(ByVal request As MaterialTrackerService.retrievePortBalancesRequest1) As MaterialTrackerService.retrievePortBalancesResponse1 Implements MaterialTrackerService.IM_MT_DS.retrievePortBalances
            Return MyBase.Channel.retrievePortBalances(request)
        End Function
        
        Public Function retrievePortBalances(ByVal RetrievePortBalancesRequest As MaterialTrackerService.RetrievePortBalancesRequest) As MaterialTrackerService.RetrievePortBalancesResponse
            Dim inValue As MaterialTrackerService.retrievePortBalancesRequest1 = New MaterialTrackerService.retrievePortBalancesRequest1()
            inValue.RetrievePortBalancesRequest = RetrievePortBalancesRequest
            Dim retVal As MaterialTrackerService.retrievePortBalancesResponse1 = CType(Me,MaterialTrackerService.IM_MT_DS).retrievePortBalances(inValue)
            Return retVal.RetrievePortBalancesResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MaterialTrackerService_IM_MT_DS_retrieveShipping(ByVal request As MaterialTrackerService.retrieveShippingRequest1) As MaterialTrackerService.retrieveShippingResponse1 Implements MaterialTrackerService.IM_MT_DS.retrieveShipping
            Return MyBase.Channel.retrieveShipping(request)
        End Function
        
        Public Function retrieveShipping(ByVal RetrieveShippingRequest As MaterialTrackerService.RetrieveShippingRequest) As MaterialTrackerService.RetrieveShippingResponse
            Dim inValue As MaterialTrackerService.retrieveShippingRequest1 = New MaterialTrackerService.retrieveShippingRequest1()
            inValue.RetrieveShippingRequest = RetrieveShippingRequest
            Dim retVal As MaterialTrackerService.retrieveShippingResponse1 = CType(Me,MaterialTrackerService.IM_MT_DS).retrieveShipping(inValue)
            Return retVal.RetrieveShippingResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MaterialTrackerService_IM_MT_DS_retrieveMETBalancing(ByVal request As MaterialTrackerService.retrieveMETBalancingRequest1) As MaterialTrackerService.retrieveMETBalancingResponse1 Implements MaterialTrackerService.IM_MT_DS.retrieveMETBalancing
            Return MyBase.Channel.retrieveMETBalancing(request)
        End Function
        
        Public Function retrieveMETBalancing(ByVal RetrieveMETBalancingRequest As MaterialTrackerService.RetrieveMETBalancingRequest) As MaterialTrackerService.RetrieveMETBalancingResponse
            Dim inValue As MaterialTrackerService.retrieveMETBalancingRequest1 = New MaterialTrackerService.retrieveMETBalancingRequest1()
            inValue.RetrieveMETBalancingRequest = RetrieveMETBalancingRequest
            Dim retVal As MaterialTrackerService.retrieveMETBalancingResponse1 = CType(Me,MaterialTrackerService.IM_MT_DS).retrieveMETBalancing(inValue)
            Return retVal.RetrieveMETBalancingResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MaterialTrackerService_IM_MT_DS_retrievePortBlending(ByVal request As MaterialTrackerService.retrievePortBlendingRequest1) As MaterialTrackerService.retrievePortBlendingResponse1 Implements MaterialTrackerService.IM_MT_DS.retrievePortBlending
            Return MyBase.Channel.retrievePortBlending(request)
        End Function
        
        Public Function retrievePortBlending(ByVal RetrievePortBlendingRequest As MaterialTrackerService.RetrievePortBlendingRequest) As MaterialTrackerService.RetrievePortBlendingResponse
            Dim inValue As MaterialTrackerService.retrievePortBlendingRequest1 = New MaterialTrackerService.retrievePortBlendingRequest1()
            inValue.RetrievePortBlendingRequest = RetrievePortBlendingRequest
            Dim retVal As MaterialTrackerService.retrievePortBlendingResponse1 = CType(Me,MaterialTrackerService.IM_MT_DS).retrievePortBlending(inValue)
            Return retVal.RetrievePortBlendingResponse
        End Function
    End Class
End Namespace
