ALTER TABLE dbo.BhpbioReportDataTags
	ADD ApprovalOrder INTEGER NOT NULL DEFAULT (3)
GO	

ALTER TABLE dbo.BhpbioApprovalData
	DROP CONSTRAINT FK_BHPBIOAPPROVALDATA_BHPBIOREPORTDATATAGS 
GO

ALTER TABLE dbo.BhpbioApprovalData
	DROP CONSTRAINT PK_BHPBIOAPPROVALDATA
GO

ALTER TABLE dbo.BhpbioReportDataTags
	DROP CONSTRAINT PK_BHPBIOREPORTDATATAGS
GO

ALTER TABLE dbo.BhpbioReportColor
	DROP CONSTRAINT PK_BhpbioReportColor
GO

ALTER TABLE dbo.BhpbioReportDataTags
	ALTER COLUMN TagId VARCHAR(63) COLLATE Database_Default NOT NULL
GO	

ALTER TABLE dbo.BhpbioApprovalData
	ALTER COLUMN TagId VARCHAR(63) COLLATE Database_Default NOT NULL
GO

ALTER TABLE dbo.BhpbioReportColor
	ALTER COLUMN TagId VARCHAR(63) COLLATE Database_Default NOT NULL
Go

ALTER TABLE dbo.BhpbioReportDataHistorical
	ALTER COLUMN TagId VARCHAR(63) COLLATE Database_Default NOT NULL
GO

ALTER TABLE dbo.BhpbioReportDataTags
	ALTER COLUMN TagId VARCHAR(63) COLLATE Database_Default NOT NULL
GO

ALTER TABLE dbo.BhpbioReportDataTags
	ADD CONSTRAINT PK_BHPBIOREPORTDATATAGS PRIMARY KEY CLUSTERED
		(TagId)
GO

ALTER TABLE dbo.BhpbioApprovalData
	ADD CONSTRAINT PK_BHPBIOAPPROVALDATA PRIMARY KEY CLUSTERED
		(TagId,	ApprovedMonth, LocationId),
	CONSTRAINT FK_BHPBIOAPPROVALDATA_BHPBIOREPORTDATATAGS FOREIGN KEY (TagId)
		REFERENCES dbo.BhpbioReportDataTags (TagId)
GO

ALTER TABLE dbo.BhpbioReportColor
	ADD CONSTRAINT PK_BhpbioReportColor PRIMARY KEY CLUSTERED
	(
		TagId
	)
GO

