//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Configuration;
using System.ServiceModel;

namespace MQ2Direct
{

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0", ConfigurationName = "IM_MQ2_DS")]
    public interface IM_MQ2_DS
    {

        // CODEGEN: Generating message contract since the operation retrieveHaulage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
            "Haulage", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
            "S/retrieveHaulageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveHaulageResponse1 retrieveHaulage(retrieveHaulageRequest1 request);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
        //    "Haulage", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
        //    "S/retrieveHaulageResponse")]
        //System.Threading.Tasks.Task<retrieveHaulageResponse1> retrieveHaulageAsync(retrieveHaulageRequest1 request);

        // CODEGEN: Generating message contract since the operation retrieveProductionMovements is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
            "ProductionMovements", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
            "S/retrieveProductionMovementsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveProductionMovementsResponse1 retrieveProductionMovements(retrieveProductionMovementsRequest1 request);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
        //    "ProductionMovements", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
        //    "S/retrieveProductionMovementsResponse")]
        //System.Threading.Tasks.Task<retrieveProductionMovementsResponse1> retrieveProductionMovementsAsync(retrieveProductionMovementsRequest1 request);

        // CODEGEN: Generating message contract since the operation retrieveStockpiles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
            "Stockpiles", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
            "S/retrieveStockpilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveStockpilesResponse1 retrieveStockpiles(retrieveStockpilesRequest1 request);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
        //    "Stockpiles", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
        //    "S/retrieveStockpilesResponse")]
        //System.Threading.Tasks.Task<retrieveStockpilesResponse1> retrieveStockpilesAsync(retrieveStockpilesRequest1 request);

        // CODEGEN: Generating message contract since the operation retrieveStockpileAdjustments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
            "StockpileAdjustments", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
            "S/retrieveStockpileAdjustmentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveStockpileAdjustmentsResponse1 retrieveStockpileAdjustments(retrieveStockpileAdjustmentsRequest1 request);

        //[System.ServiceModel.OperationContractAttribute(Action = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/retrieve" +
        //    "StockpileAdjustments", ReplyAction = "http://www.bhpbilliton.com/waio/F1F2F3ReconciliationDataService/MQ2/v1.0/IM_MQ2_D" +
        //    "S/retrieveStockpileAdjustmentsResponse")]
        //System.Threading.Tasks.Task<retrieveStockpileAdjustmentsResponse1> retrieveStockpileAdjustmentsAsync(retrieveStockpileAdjustmentsRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveHaulageRequest
    {

        private string mineSiteCodeField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MineSiteCode
        {
            get
            {
                return this.mineSiteCodeField;
            }
            set
            {
                this.mineSiteCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class AdjustmentType
    {

        private Location locationField;

        private string stockpileIDField;

        private string adjustmentType1Field;

        private System.DateTime adjustmentDateField;

        private bool adjustmentDateFieldSpecified;

        private decimal tonnesField;

        private bool tonnesFieldSpecified;

        private decimal finesPercentField;

        private bool finesPercentFieldSpecified;

        private decimal lumpPercentField;

        private bool lumpPercentFieldSpecified;

        private decimal bcmField;

        private bool bcmFieldSpecified;

        private System.DateTime lastModifiedTimeField;

        private bool lastModifiedTimeFieldSpecified;

        private Grade[] gradeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string StockpileID
        {
            get
            {
                return this.stockpileIDField;
            }
            set
            {
                this.stockpileIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjustmentType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string AdjustmentType1
        {
            get
            {
                return this.adjustmentType1Field;
            }
            set
            {
                this.adjustmentType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime AdjustmentDate
        {
            get
            {
                return this.adjustmentDateField;
            }
            set
            {
                this.adjustmentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdjustmentDateSpecified
        {
            get
            {
                return this.adjustmentDateFieldSpecified;
            }
            set
            {
                this.adjustmentDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal Tonnes
        {
            get
            {
                return this.tonnesField;
            }
            set
            {
                this.tonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TonnesSpecified
        {
            get
            {
                return this.tonnesFieldSpecified;
            }
            set
            {
                this.tonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal FinesPercent
        {
            get
            {
                return this.finesPercentField;
            }
            set
            {
                this.finesPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinesPercentSpecified
        {
            get
            {
                return this.finesPercentFieldSpecified;
            }
            set
            {
                this.finesPercentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public decimal LumpPercent
        {
            get
            {
                return this.lumpPercentField;
            }
            set
            {
                this.lumpPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LumpPercentSpecified
        {
            get
            {
                return this.lumpPercentFieldSpecified;
            }
            set
            {
                this.lumpPercentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public decimal Bcm
        {
            get
            {
                return this.bcmField;
            }
            set
            {
                this.bcmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BcmSpecified
        {
            get
            {
                return this.bcmFieldSpecified;
            }
            set
            {
                this.bcmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public System.DateTime LastModifiedTime
        {
            get
            {
                return this.lastModifiedTimeField;
            }
            set
            {
                this.lastModifiedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastModifiedTimeSpecified
        {
            get
            {
                return this.lastModifiedTimeFieldSpecified;
            }
            set
            {
                this.lastModifiedTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grade", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public Grade[] Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class Location
    {

        private string mineField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Mine
        {
            get
            {
                return this.mineField;
            }
            set
            {
                this.mineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class Grade
    {

        private string nameField;

        private decimal sampleValueField;

        private bool sampleValueFieldSpecified;

        private decimal headValueField;

        private bool headValueFieldSpecified;

        private decimal finesValueField;

        private bool finesValueFieldSpecified;

        private decimal lumpValueField;

        private bool lumpValueFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal SampleValue
        {
            get
            {
                return this.sampleValueField;
            }
            set
            {
                this.sampleValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SampleValueSpecified
        {
            get
            {
                return this.sampleValueFieldSpecified;
            }
            set
            {
                this.sampleValueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public decimal HeadValue
        {
            get
            {
                return this.headValueField;
            }
            set
            {
                this.headValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeadValueSpecified
        {
            get
            {
                return this.headValueFieldSpecified;
            }
            set
            {
                this.headValueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public decimal FinesValue
        {
            get
            {
                return this.finesValueField;
            }
            set
            {
                this.finesValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinesValueSpecified
        {
            get
            {
                return this.finesValueFieldSpecified;
            }
            set
            {
                this.finesValueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal LumpValue
        {
            get
            {
                return this.lumpValueField;
            }
            set
            {
                this.lumpValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LumpValueSpecified
        {
            get
            {
                return this.lumpValueFieldSpecified;
            }
            set
            {
                this.lumpValueFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class StockpileType
    {

        private Location locationField;

        private string nameField;

        private string businessIdField;

        private string stockpileType1Field;

        private string descriptionField;

        private string oreTypeField;

        private string typeField;

        private string activeField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private string productSizeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string BusinessId
        {
            get
            {
                return this.businessIdField;
            }
            set
            {
                this.businessIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StockpileType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string StockpileType1
        {
            get
            {
                return this.stockpileType1Field;
            }
            set
            {
                this.stockpileType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string OreType
        {
            get
            {
                return this.oreTypeField;
            }
            set
            {
                this.oreTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string ProductSize
        {
            get
            {
                return this.productSizeField;
            }
            set
            {
                this.productSizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class ProdMovesTransactionType
    {

        private Location locationField;

        private System.DateTime transactionDateField;

        private bool transactionDateFieldSpecified;

        private string sourceField;

        private string sourceTypeField;

        private string sourceMineSiteField;

        private string destinationField;

        private string destinationTypeField;

        private string destinationMineSiteField;

        private string typeField;

        private decimal tonnesField;

        private bool tonnesFieldSpecified;

        private string productSizeField;

        private System.DateTime lastModifiedTimeField;

        private bool lastModifiedTimeFieldSpecified;

        private string sampleSourceField;

        private decimal sampleTonnesField;

        private bool sampleTonnesFieldSpecified;

        private decimal sampleCountField;

        private bool sampleCountFieldSpecified;

        private Grade[] gradeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDateSpecified
        {
            get
            {
                return this.transactionDateFieldSpecified;
            }
            set
            {
                this.transactionDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string SourceType
        {
            get
            {
                return this.sourceTypeField;
            }
            set
            {
                this.sourceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string SourceMineSite
        {
            get
            {
                return this.sourceMineSiteField;
            }
            set
            {
                this.sourceMineSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string DestinationType
        {
            get
            {
                return this.destinationTypeField;
            }
            set
            {
                this.destinationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string DestinationMineSite
        {
            get
            {
                return this.destinationMineSiteField;
            }
            set
            {
                this.destinationMineSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal Tonnes
        {
            get
            {
                return this.tonnesField;
            }
            set
            {
                this.tonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TonnesSpecified
        {
            get
            {
                return this.tonnesFieldSpecified;
            }
            set
            {
                this.tonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string ProductSize
        {
            get
            {
                return this.productSizeField;
            }
            set
            {
                this.productSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public System.DateTime LastModifiedTime
        {
            get
            {
                return this.lastModifiedTimeField;
            }
            set
            {
                this.lastModifiedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastModifiedTimeSpecified
        {
            get
            {
                return this.lastModifiedTimeFieldSpecified;
            }
            set
            {
                this.lastModifiedTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string SampleSource
        {
            get
            {
                return this.sampleSourceField;
            }
            set
            {
                this.sampleSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public decimal SampleTonnes
        {
            get
            {
                return this.sampleTonnesField;
            }
            set
            {
                this.sampleTonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SampleTonnesSpecified
        {
            get
            {
                return this.sampleTonnesFieldSpecified;
            }
            set
            {
                this.sampleTonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public decimal SampleCount
        {
            get
            {
                return this.sampleCountField;
            }
            set
            {
                this.sampleCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SampleCountSpecified
        {
            get
            {
                return this.sampleCountFieldSpecified;
            }
            set
            {
                this.sampleCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grade", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public Grade[] Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class HaulageTransactionType
    {

        private Location locationField;

        private System.DateTime transactionDateField;

        private bool transactionDateFieldSpecified;

        private string sourceField;

        private string sourceMineSiteField;

        private string destinationMineSiteField;

        private string sourceLocationTypeField;

        private string destinationField;

        private string destinationTypeField;

        private string typeField;

        private decimal bestTonnesField;

        private bool bestTonnesFieldSpecified;

        private decimal hauledTonnesField;

        private bool hauledTonnesFieldSpecified;

        private decimal aerialSurveyTonnesField;

        private bool aerialSurveyTonnesFieldSpecified;

        private decimal groundSurveyTonnesField;

        private bool groundSurveyTonnesFieldSpecified;

        private decimal lumpPercentField;

        private bool lumpPercentFieldSpecified;

        private System.DateTime lastModifiedTimeField;

        private bool lastModifiedTimeFieldSpecified;

        private Grade[] gradeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDateSpecified
        {
            get
            {
                return this.transactionDateFieldSpecified;
            }
            set
            {
                this.transactionDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string SourceMineSite
        {
            get
            {
                return this.sourceMineSiteField;
            }
            set
            {
                this.sourceMineSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string DestinationMineSite
        {
            get
            {
                return this.destinationMineSiteField;
            }
            set
            {
                this.destinationMineSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string SourceLocationType
        {
            get
            {
                return this.sourceLocationTypeField;
            }
            set
            {
                this.sourceLocationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string DestinationType
        {
            get
            {
                return this.destinationTypeField;
            }
            set
            {
                this.destinationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public decimal BestTonnes
        {
            get
            {
                return this.bestTonnesField;
            }
            set
            {
                this.bestTonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestTonnesSpecified
        {
            get
            {
                return this.bestTonnesFieldSpecified;
            }
            set
            {
                this.bestTonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public decimal HauledTonnes
        {
            get
            {
                return this.hauledTonnesField;
            }
            set
            {
                this.hauledTonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HauledTonnesSpecified
        {
            get
            {
                return this.hauledTonnesFieldSpecified;
            }
            set
            {
                this.hauledTonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public decimal AerialSurveyTonnes
        {
            get
            {
                return this.aerialSurveyTonnesField;
            }
            set
            {
                this.aerialSurveyTonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AerialSurveyTonnesSpecified
        {
            get
            {
                return this.aerialSurveyTonnesFieldSpecified;
            }
            set
            {
                this.aerialSurveyTonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public decimal GroundSurveyTonnes
        {
            get
            {
                return this.groundSurveyTonnesField;
            }
            set
            {
                this.groundSurveyTonnesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroundSurveyTonnesSpecified
        {
            get
            {
                return this.groundSurveyTonnesFieldSpecified;
            }
            set
            {
                this.groundSurveyTonnesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public decimal LumpPercent
        {
            get
            {
                return this.lumpPercentField;
            }
            set
            {
                this.lumpPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LumpPercentSpecified
        {
            get
            {
                return this.lumpPercentFieldSpecified;
            }
            set
            {
                this.lumpPercentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public System.DateTime LastModifiedTime
        {
            get
            {
                return this.lastModifiedTimeField;
            }
            set
            {
                this.lastModifiedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastModifiedTimeSpecified
        {
            get
            {
                return this.lastModifiedTimeFieldSpecified;
            }
            set
            {
                this.lastModifiedTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grade", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public Grade[] Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class Status
    {

        private string statusMessageField;

        private bool statusFlagField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string StatusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public bool StatusFlag
        {
            get
            {
                return this.statusFlagField;
            }
            set
            {
                this.statusFlagField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveHaulageResponse
    {

        private Status statusField;

        private HaulageTransactionType[] haulageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transaction", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public HaulageTransactionType[] Haulage
        {
            get
            {
                return this.haulageField;
            }
            set
            {
                this.haulageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveHaulageRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveHaulageRequest RetrieveHaulageRequest;

        public retrieveHaulageRequest1()
        {
        }

        public retrieveHaulageRequest1(RetrieveHaulageRequest RetrieveHaulageRequest)
        {
            this.RetrieveHaulageRequest = RetrieveHaulageRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveHaulageResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveHaulageResponse RetrieveHaulageResponse;

        public retrieveHaulageResponse1()
        {
        }

        public retrieveHaulageResponse1(RetrieveHaulageResponse RetrieveHaulageResponse)
        {
            this.RetrieveHaulageResponse = RetrieveHaulageResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveProductionMovementsRequest
    {

        private string mineSiteCodeField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MineSiteCode
        {
            get
            {
                return this.mineSiteCodeField;
            }
            set
            {
                this.mineSiteCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveProductionMovementsResponse
    {

        private Status statusField;

        private ProdMovesTransactionType[] productionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transaction", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ProdMovesTransactionType[] Production
        {
            get
            {
                return this.productionField;
            }
            set
            {
                this.productionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveProductionMovementsRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveProductionMovementsRequest RetrieveProductionMovementsRequest;

        public retrieveProductionMovementsRequest1()
        {
        }

        public retrieveProductionMovementsRequest1(RetrieveProductionMovementsRequest RetrieveProductionMovementsRequest)
        {
            this.RetrieveProductionMovementsRequest = RetrieveProductionMovementsRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveProductionMovementsResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveProductionMovementsResponse RetrieveProductionMovementsResponse;

        public retrieveProductionMovementsResponse1()
        {
        }

        public retrieveProductionMovementsResponse1(RetrieveProductionMovementsResponse RetrieveProductionMovementsResponse)
        {
            this.RetrieveProductionMovementsResponse = RetrieveProductionMovementsResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveStockpilesRequest
    {

        private string mineSiteCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MineSiteCode
        {
            get
            {
                return this.mineSiteCodeField;
            }
            set
            {
                this.mineSiteCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveStockpilesResponse
    {

        private Status statusField;

        private StockpileType[] stockpilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Stockpile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public StockpileType[] Stockpiles
        {
            get
            {
                return this.stockpilesField;
            }
            set
            {
                this.stockpilesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveStockpilesRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveStockpilesRequest RetrieveStockpilesRequest;

        public retrieveStockpilesRequest1()
        {
        }

        public retrieveStockpilesRequest1(RetrieveStockpilesRequest RetrieveStockpilesRequest)
        {
            this.RetrieveStockpilesRequest = RetrieveStockpilesRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveStockpilesResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveStockpilesResponse RetrieveStockpilesResponse;

        public retrieveStockpilesResponse1()
        {
        }

        public retrieveStockpilesResponse1(RetrieveStockpilesResponse RetrieveStockpilesResponse)
        {
            this.RetrieveStockpilesResponse = RetrieveStockpilesResponse;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveStockpileAdjustmentsRequest
    {

        private string mineSiteCodeField;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        private System.DateTime endDateField;

        private bool endDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string MineSiteCode
        {
            get
            {
                return this.mineSiteCodeField;
            }
            set
            {
                this.mineSiteCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService")]
    public partial class RetrieveStockpileAdjustmentsResponse
    {

        private Status statusField;

        private AdjustmentType[] stockpileAdjustmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Adjustment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public AdjustmentType[] StockpileAdjustment
        {
            get
            {
                return this.stockpileAdjustmentField;
            }
            set
            {
                this.stockpileAdjustmentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveStockpileAdjustmentsRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveStockpileAdjustmentsRequest RetrieveStockpileAdjustmentsRequest;

        public retrieveStockpileAdjustmentsRequest1()
        {
        }

        public retrieveStockpileAdjustmentsRequest1(RetrieveStockpileAdjustmentsRequest RetrieveStockpileAdjustmentsRequest)
        {
            this.RetrieveStockpileAdjustmentsRequest = RetrieveStockpileAdjustmentsRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveStockpileAdjustmentsResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.bhpbilliton.com/waio/F1F2F3DataService", Order = 0)]
        public RetrieveStockpileAdjustmentsResponse RetrieveStockpileAdjustmentsResponse;

        public retrieveStockpileAdjustmentsResponse1()
        {
        }

        public retrieveStockpileAdjustmentsResponse1(RetrieveStockpileAdjustmentsResponse RetrieveStockpileAdjustmentsResponse)
        {
            this.RetrieveStockpileAdjustmentsResponse = RetrieveStockpileAdjustmentsResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IM_MQ2_DSChannel : IM_MQ2_DS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class M_MQ2_DSClient : System.ServiceModel.ClientBase<IM_MQ2_DS>, IM_MQ2_DS
    {

        public M_MQ2_DSClient()
        {
        }

        public M_MQ2_DSClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public M_MQ2_DSClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public M_MQ2_DSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public M_MQ2_DSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        retrieveHaulageResponse1 IM_MQ2_DS.retrieveHaulage(retrieveHaulageRequest1 request)
        {
            return base.Channel.retrieveHaulage(request);
        }

        public RetrieveHaulageResponse retrieveHaulage(RetrieveHaulageRequest RetrieveHaulageRequest)
        {
            retrieveHaulageRequest1 inValue = new retrieveHaulageRequest1();
            inValue.RetrieveHaulageRequest = RetrieveHaulageRequest;
            retrieveHaulageResponse1 retVal = ((IM_MQ2_DS)(this)).retrieveHaulage(inValue);
            return retVal.RetrieveHaulageResponse;
        }

        //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        //System.Threading.Tasks.Task<retrieveHaulageResponse1> IM_MQ2_DS.retrieveHaulageAsync(retrieveHaulageRequest1 request)
        //{
        //    return base.Channel.retrieveHaulageAsync(request);
        //}

        //public System.Threading.Tasks.Task<retrieveHaulageResponse1> retrieveHaulageAsync(RetrieveHaulageRequest RetrieveHaulageRequest)
        //{
        //    retrieveHaulageRequest1 inValue = new retrieveHaulageRequest1();
        //    inValue.RetrieveHaulageRequest = RetrieveHaulageRequest;
        //    return ((IM_MQ2_DS)(this)).retrieveHaulageAsync(inValue);
        //}

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        retrieveProductionMovementsResponse1 IM_MQ2_DS.retrieveProductionMovements(retrieveProductionMovementsRequest1 request)
        {
            return base.Channel.retrieveProductionMovements(request);
        }

        public RetrieveProductionMovementsResponse retrieveProductionMovements(RetrieveProductionMovementsRequest RetrieveProductionMovementsRequest)
        {
            retrieveProductionMovementsRequest1 inValue = new retrieveProductionMovementsRequest1();
            inValue.RetrieveProductionMovementsRequest = RetrieveProductionMovementsRequest;
            retrieveProductionMovementsResponse1 retVal = ((IM_MQ2_DS)(this)).retrieveProductionMovements(inValue);
            return retVal.RetrieveProductionMovementsResponse;
        }

        //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        //System.Threading.Tasks.Task<retrieveProductionMovementsResponse1> IM_MQ2_DS.retrieveProductionMovementsAsync(retrieveProductionMovementsRequest1 request)
        //{
        //    return base.Channel.retrieveProductionMovementsAsync(request);
        //}

        //public System.Threading.Tasks.Task<retrieveProductionMovementsResponse1> retrieveProductionMovementsAsync(RetrieveProductionMovementsRequest RetrieveProductionMovementsRequest)
        //{
        //    retrieveProductionMovementsRequest1 inValue = new retrieveProductionMovementsRequest1();
        //    inValue.RetrieveProductionMovementsRequest = RetrieveProductionMovementsRequest;
        //    return ((IM_MQ2_DS)(this)).retrieveProductionMovementsAsync(inValue);
        //}

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        retrieveStockpilesResponse1 IM_MQ2_DS.retrieveStockpiles(retrieveStockpilesRequest1 request)
        {
            return base.Channel.retrieveStockpiles(request);
        }

        public RetrieveStockpilesResponse retrieveStockpiles(RetrieveStockpilesRequest RetrieveStockpilesRequest)
        {
            retrieveStockpilesRequest1 inValue = new retrieveStockpilesRequest1();
            inValue.RetrieveStockpilesRequest = RetrieveStockpilesRequest;
            retrieveStockpilesResponse1 retVal = ((IM_MQ2_DS)(this)).retrieveStockpiles(inValue);
            return retVal.RetrieveStockpilesResponse;
        }

        //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        //System.Threading.Tasks.Task<retrieveStockpilesResponse1> IM_MQ2_DS.retrieveStockpilesAsync(retrieveStockpilesRequest1 request)
        //{
        //    return base.Channel.retrieveStockpilesAsync(request);
        //}

        //public System.Threading.Tasks.Task<retrieveStockpilesResponse1> retrieveStockpilesAsync(RetrieveStockpilesRequest RetrieveStockpilesRequest)
        //{
        //    retrieveStockpilesRequest1 inValue = new retrieveStockpilesRequest1();
        //    inValue.RetrieveStockpilesRequest = RetrieveStockpilesRequest;
        //    return ((IM_MQ2_DS)(this)).retrieveStockpilesAsync(inValue);
        //}

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        retrieveStockpileAdjustmentsResponse1 IM_MQ2_DS.retrieveStockpileAdjustments(retrieveStockpileAdjustmentsRequest1 request)
        {
            return base.Channel.retrieveStockpileAdjustments(request);
        }

        public RetrieveStockpileAdjustmentsResponse retrieveStockpileAdjustments(RetrieveStockpileAdjustmentsRequest RetrieveStockpileAdjustmentsRequest)
        {
            retrieveStockpileAdjustmentsRequest1 inValue = new retrieveStockpileAdjustmentsRequest1();
            inValue.RetrieveStockpileAdjustmentsRequest = RetrieveStockpileAdjustmentsRequest;
            retrieveStockpileAdjustmentsResponse1 retVal = ((IM_MQ2_DS)(this)).retrieveStockpileAdjustments(inValue);
            return retVal.RetrieveStockpileAdjustmentsResponse;
        }

        //[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        //System.Threading.Tasks.Task<retrieveStockpileAdjustmentsResponse1> IM_MQ2_DS.retrieveStockpileAdjustmentsAsync(retrieveStockpileAdjustmentsRequest1 request)
        //{
        //    return base.Channel.retrieveStockpileAdjustmentsAsync(request);
        //}

        //public System.Threading.Tasks.Task<retrieveStockpileAdjustmentsResponse1> retrieveStockpileAdjustmentsAsync(RetrieveStockpileAdjustmentsRequest RetrieveStockpileAdjustmentsRequest)
        //{
        //    retrieveStockpileAdjustmentsRequest1 inValue = new retrieveStockpileAdjustmentsRequest1();
        //    inValue.RetrieveStockpileAdjustmentsRequest = RetrieveStockpileAdjustmentsRequest;
        //    return ((IM_MQ2_DS)(this)).retrieveStockpileAdjustmentsAsync(inValue);
        //}
    }
}
