-------------
-- BHPBIO PRE

-- de-link the BHPBIO tables
ALTER TABLE dbo.BhpbioApprovalData
	DROP CONSTRAINT FK_BHPBIOAPPROVALDATA_USER
GO

ALTER TABLE dbo.BhpbioApprovalDigblock
	DROP CONSTRAINT FK_BHPBIOAPPROVALDIGBLOCK_USER
GO

ALTER TABLE dbo.BhpbioSecurityRoleLocation
	DROP CONSTRAINT FK_BHPBIOSECURITYROLELOCATION_SECURITYROLE

ALTER TABLE dbo.SecurityApplicationRole
	DROP CONSTRAINT FK__SECURITY_APPLICATION_ROLE__SECURITY_ROLE

ALTER TABLE dbo.SecurityRoleOption
	DROP CONSTRAINT FK__SECURITY_ROLE_OPTION__SECURITY_ROLE
GO
