BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO

IF OBJECT_ID('Staging.TmpAsDroppedImport') IS NOT NULL
     DROP TABLE Staging.TmpAsDroppedImport 
GO 

CREATE TABLE Staging.TmpAsDroppedImport
	(
	RowId int NOT NULL IDENTITY (1, 1),
	SITE varchar(31) NULL,
	PIT varchar(31) NULL,
	MQ2_PIT_CODE varchar(31) NULL,
	BENCH varchar(31) NULL,
	PATTERN_ID int NULL,
	PATTERN_NUMBER varchar(31) NULL,
	BLOCK_NAME varchar(50) NULL,
	BLOCK_FULL_NAME varchar(50) NULL,
	BMF bit NULL,
	MODEL varchar(31) NULL,
	ORE_TYPE varchar(31) NULL,
	AD_LUMP_PCT real NULL,
	AD_LUMP_FE real NULL,
	AD_LUMP_P real NULL,
	AD_LUMP_SIO2 real NULL,
	AD_LUMP_AL2O3 real NULL,
	AD_LUMP_LOI real NULL,
	AD_LUMP_H2O real NULL,
	AD_FINES_FE real NULL,
	AD_FINES_P real NULL,
	AD_FINES_SIO2 real NULL,
	AD_FINES_AL2O3 real NULL,
	AD_FINES_LOI real NULL,
	AD_FINES_H2O real NULL,

	AS_LUMP_H2O real NULL,
	AS_FINES_H2O real NULL,

	UF real NULL,
	AS_FINES_UF real NULL,
	AD_FINES_UF real NULL,
	ImportDate datetime NOT NULL,
	ImportFile varchar(255) NOT NULL,
	StagingBlockModelId int NULL,
	Message nvarchar(MAX) NULL,
	Processed int NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE Staging.TmpAsDroppedImport ADD CONSTRAINT
	DF_AsDroppedImport_Processed DEFAULT 0 FOR Processed
GO

ALTER TABLE Staging.TmpAsDroppedImport ADD CONSTRAINT
	PK_AsDroppedImport PRIMARY KEY CLUSTERED 
	(
	RowId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE Staging.TmpAsDroppedImport SET (LOCK_ESCALATION = TABLE)
GO

CREATE NONCLUSTERED INDEX [IX_AsDroppedImport_Processed] ON [Staging].TmpAsDroppedImport
(
	[Processed] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_AsDroppedImport_MappedBlockModelId] ON [Staging].TmpAsDroppedImport
(
	StagingBlockModelId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

COMMIT